version: "3"

services:
  freshrss_postgresql:
    image: postgres
    restart: always
    container_name: freshrss-db
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=freshrss
      - POSTGRES_PASSWORD=freshrss
      - POSTGRES_DB=freshrss

  freshrss:
    image: freshrss/freshrss
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - freshrss_postgresql
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN=*/5
      - TZ=America/Chicago
    labels:
      kompose.service.type: LoadBalancer

volumes:
  pgsql_data:
  freshrss_data:
  freshrss_extensions:
