apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"kompose convert","kompose.service.type":"LoadBalancer","kompose.version":"1.21.0 (992df58d8)"},"creationTimestamp":null,"labels":{"io.kompose.service":"freshrss"},"name":"freshrss","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"io.kompose.service":"freshrss"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"kompose.cmd":"kompose convert","kompose.service.type":"LoadBalancer","kompose.version":"1.21.0 (992df58d8)"},"creationTimestamp":null,"labels":{"io.kompose.service":"freshrss"}},"spec":{"containers":[{"env":[{"name":"CRON_MIN","value":"*/5"},{"name":"TZ","value":"America/Chicago"}],"image":"freshrss/freshrss","imagePullPolicy":"","name":"freshrss","ports":[{"containerPort":80}],"resources":{},"volumeMounts":[{"mountPath":"/var/www/FreshRSS/data","name":"freshrss-data"},{"mountPath":"/var/www/FreshRSS/extensions","name":"freshrss-extensions"}]}],"restartPolicy":"Always","serviceAccountName":"","volumes":[{"name":"freshrss-data","persistentVolumeClaim":{"claimName":"freshrss-data"}},{"name":"freshrss-extensions","persistentVolumeClaim":{"claimName":"freshrss-extensions"}}]}}},"status":{}}
  creationTimestamp: "2020-05-15T04:58:58Z"
  generation: 1
  labels:
    io.kompose.service: freshrss
  name: freshrss
  namespace: default
  resourceVersion: "8206"
  selfLink: /apis/apps/v1/namespaces/default/deployments/freshrss
  uid: c940155e-9668-11ea-9ec2-42010a8e0027
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: freshrss
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: freshrss
    spec:
      containers:
      - env:
        - name: CRON_MIN
          value: '*/5'
        - name: TZ
          value: America/Chicago
        image: freshrss/freshrss
        imagePullPolicy: Always
        name: freshrss
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/FreshRSS/data
          name: freshrss-data
        - mountPath: /var/www/FreshRSS/extensions
          name: freshrss-extensions
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: freshrss-data
        persistentVolumeClaim:
          claimName: freshrss-data
      - name: freshrss-extensions
        persistentVolumeClaim:
          claimName: freshrss-extensions
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-05-15T05:01:01Z"
    lastUpdateTime: "2020-05-15T05:01:01Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-05-15T04:58:58Z"
    lastUpdateTime: "2020-05-15T05:01:01Z"
    message: ReplicaSet "freshrss-7d9c694bc6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
